<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <title></title>
    </head>
    <body>
        <h1>Neues Seminar anlegen</h1>
        <form action="seminare.php?action=add" method="post">
            Titel: <input type="text" name="titel" /><br />
            Beschreibung: <textarea name="beschreibung"></textarea><br />
            Preis: <input type="text" name="preis" /><br />
            Kategorie: <input type="text" name="kategorie" /><br />
            <input type="submit" value="Seminar anlegen" />
        </form>
    </body>
</html>
