<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Neuen Seminartermin anlegen</title>
    </head>
    <body>
        <h1>Neuen Seminartermin anlegen</h1>

        <form action="seminartermine.php?action=add" method="post">
            Seminar:
            <select name="seminar_id">
                <?php foreach ($seminare as $seminar) { ?>
                    <option value="<?php echo $seminar->getId() ?>"><?php echo $seminar ?></option>
                <?php } ?>
            </select><br />
            Beginn: <input type="text" name="beginn" /><br />
            Ende: <input type="text" name="ende" /><br />
            Raum: <input type="text" name="raum" /><br />
            <input type="submit" value="Termin anlegen" />
        </form>
    </body>
</html>
